// <auto-generated />
using System;
using Dhole.AI.Persistence.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dhole.AI.Persistence.Migrations
{
    [DbContext(typeof(ServiceDbContext))]
    [Migration("20260720213041_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ai")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CustomCodeFramework.Messaging.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConsumerService")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("consumer_service");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("event_name");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("event_type");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("SourceService")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_service");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_inbox_messages");

                    b.HasIndex("EventId", "ConsumerService")
                        .IsUnique();

                    b.HasIndex("Status", "CreatedAtUtc");

                    b.ToTable("inbox_messages", "ai");
                });

            modelBuilder.Entity("CustomCodeFramework.Messaging.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("event_name");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("event_type");

                    b.Property<string>("HeadersJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("headers_json");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("SourceService")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_service");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_outbox_messages");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("Status", "CreatedAtUtc");

                    b.ToTable("outbox_messages", "ai");
                });

            modelBuilder.Entity("Dhole.AI.Domain.Connections.Entities.AiConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("base_url");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastHealthCheckAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_health_check_at_utc");

                    b.Property<string>("LastHealthError")
                        .HasColumnType("text")
                        .HasColumnName("last_health_error");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider_type");

                    b.Property<string>("SecretReference")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("secret_reference");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("timeout_seconds");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_ai_connections");

                    b.HasIndex("IsActive");

                    b.HasIndex("LastHealthCheckAtUtc");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_ai_connections_name")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("ProviderType");

                    b.HasIndex("Status");

                    b.ToTable("AiConnections", "ai");
                });

            modelBuilder.Entity("Dhole.AI.Domain.Executions.Entities.AiExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at_utc");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<long>("DurationMilliseconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("duration_milliseconds");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<decimal>("EstimatedCost")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasDefaultValue(0m)
                        .HasColumnName("estimated_cost");

                    b.Property<string>("ExecutionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("execution_type");

                    b.Property<string>("FinishReason")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("finish_reason");

                    b.Property<int>("InputTokens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("input_tokens");

                    b.Property<string>("OutputReference")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("output_reference");

                    b.Property<int>("OutputTokens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("output_tokens");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("ProfileKey")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("profile_key");

                    b.Property<Guid?>("PromptTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("prompt_template_id");

                    b.Property<string>("RequestHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("request_hash");

                    b.Property<Guid?>("SelectedConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("selected_connection_id");

                    b.Property<Guid?>("SelectedModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("selected_model_id");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_ai_executions");

                    b.HasIndex("CompletedAtUtc");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("ExecutionType");

                    b.HasIndex("ProfileId");

                    b.HasIndex("ProfileKey");

                    b.HasIndex("PromptTemplateId");

                    b.HasIndex("RequestHash");

                    b.HasIndex("SelectedConnectionId");

                    b.HasIndex("SelectedModelId");

                    b.HasIndex("StartedAtUtc");

                    b.HasIndex("Status");

                    b.HasIndex("ProfileKey", "Status", "StartedAtUtc")
                        .HasDatabaseName("ix_ai_executions_profile_status_started");

                    b.ToTable("AiExecutions", "ai");
                });

            modelBuilder.Entity("Dhole.AI.Domain.Executions.Entities.AiExecutionAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_number");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("connection_id");

                    b.Property<long>("DurationMilliseconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("duration_milliseconds");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<decimal>("EstimatedCost")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasDefaultValue(0m)
                        .HasColumnName("estimated_cost");

                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("execution_id");

                    b.Property<string>("ExternalModelId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("external_model_id");

                    b.Property<string>("FinishReason")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("finish_reason");

                    b.Property<int>("InputTokens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("input_tokens");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_id");

                    b.Property<int>("OutputTokens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("output_tokens");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider_type");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_ai_execution_attempts");

                    b.HasIndex("ConnectionId");

                    b.HasIndex("ExecutionId");

                    b.HasIndex("ModelId");

                    b.HasIndex("ProviderType");

                    b.HasIndex("StartedAtUtc");

                    b.HasIndex("Status");

                    b.HasIndex("ExecutionId", "AttemptNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_ai_execution_attempts_execution_number");

                    b.ToTable("AiExecutionAttempts", "ai");
                });

            modelBuilder.Entity("Dhole.AI.Domain.Models.Entities.AiModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Capabilities")
                        .HasColumnType("integer")
                        .HasColumnName("capabilities");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("connection_id");

                    b.Property<int?>("ContextWindow")
                        .HasColumnType("integer")
                        .HasColumnName("context_window");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<string>("ExternalModelId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("external_model_id");

                    b.Property<decimal?>("InputCostPerMillionTokens")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("input_cost_per_million_tokens");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsLocal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_local");

                    b.Property<DateTime?>("LastAvailabilityCheckAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_availability_check_at_utc");

                    b.Property<string>("LastAvailabilityError")
                        .HasColumnType("text")
                        .HasColumnName("last_availability_error");

                    b.Property<int?>("MaximumOutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("maximum_output_tokens");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<decimal?>("OutputCostPerMillionTokens")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("output_cost_per_million_tokens");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_ai_models");

                    b.HasIndex("Capabilities");

                    b.HasIndex("ConnectionId");

                    b.HasIndex("ExternalModelId");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsLocal");

                    b.HasIndex("Name");

                    b.HasIndex("Status");

                    b.HasIndex("ConnectionId", "ExternalModelId")
                        .IsUnique()
                        .HasDatabaseName("ux_ai_models_connection_external_model")
                        .HasFilter("is_deleted = false");

                    b.ToTable("AiModels", "ai");
                });

            modelBuilder.Entity("Dhole.AI.Domain.Profiles.Entities.AiProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("JsonSchema")
                        .HasColumnType("text")
                        .HasColumnName("json_schema");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("key");

                    b.Property<int>("MaximumOutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("maximum_output_tokens");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid?>("PromptTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("prompt_template_id");

                    b.Property<string>("ResponseFormat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("response_format");

                    b.Property<string>("RoutingMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("routing_mode");

                    b.Property<decimal>("Temperature")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("temperature");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("timeout_seconds");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_ai_profiles");

                    b.HasIndex("IsActive");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ux_ai_profiles_key")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("Name");

                    b.HasIndex("PromptTemplateId");

                    b.HasIndex("ResponseFormat");

                    b.HasIndex("RoutingMode");

                    b.ToTable("AiProfiles", "ai");
                });

            modelBuilder.Entity("Dhole.AI.Domain.Profiles.Entities.AiProfileModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsFallback")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_fallback");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_id");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.HasKey("Id")
                        .HasName("p_k_ai_profile_models");

                    b.HasIndex("IsFallback");

                    b.HasIndex("ModelId");

                    b.HasIndex("Priority");

                    b.HasIndex("ProfileId");

                    b.HasIndex("ProfileId", "ModelId")
                        .IsUnique()
                        .HasDatabaseName("ux_ai_profile_models_profile_model");

                    b.HasIndex("ProfileId", "Priority")
                        .IsUnique()
                        .HasDatabaseName("ux_ai_profile_models_profile_priority");

                    b.ToTable("AiProfileModels", "ai");
                });

            modelBuilder.Entity("Dhole.AI.Domain.PromptTemplates.Entities.AiPromptTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("SystemPrompt")
                        .HasColumnType("text")
                        .HasColumnName("system_prompt");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<string>("UserPromptTemplate")
                        .HasColumnType("text")
                        .HasColumnName("user_prompt_template");

                    b.Property<string>("VariablesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("variables_json");

                    b.HasKey("Id")
                        .HasName("p_k_ai_prompt_templates");

                    b.HasIndex("IsActive");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ux_ai_prompt_templates_key")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("Name");

                    b.ToTable("AiPromptTemplates", "ai");
                });

            modelBuilder.Entity("Dhole.AI.Domain.Executions.Entities.AiExecution", b =>
                {
                    b.HasOne("Dhole.AI.Domain.Profiles.Entities.AiProfile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dhole.AI.Domain.PromptTemplates.Entities.AiPromptTemplate", null)
                        .WithMany()
                        .HasForeignKey("PromptTemplateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Dhole.AI.Domain.Connections.Entities.AiConnection", null)
                        .WithMany()
                        .HasForeignKey("SelectedConnectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Dhole.AI.Domain.Models.Entities.AiModel", null)
                        .WithMany()
                        .HasForeignKey("SelectedModelId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Dhole.AI.Domain.Executions.Entities.AiExecutionAttempt", b =>
                {
                    b.HasOne("Dhole.AI.Domain.Connections.Entities.AiConnection", null)
                        .WithMany()
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dhole.AI.Domain.Executions.Entities.AiExecution", null)
                        .WithMany("Attempts")
                        .HasForeignKey("ExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_ai_execution_attempts_ai_executions_ai_execution_id");

                    b.HasOne("Dhole.AI.Domain.Models.Entities.AiModel", null)
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dhole.AI.Domain.Models.Entities.AiModel", b =>
                {
                    b.HasOne("Dhole.AI.Domain.Connections.Entities.AiConnection", null)
                        .WithMany()
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dhole.AI.Domain.Profiles.Entities.AiProfile", b =>
                {
                    b.HasOne("Dhole.AI.Domain.PromptTemplates.Entities.AiPromptTemplate", null)
                        .WithMany()
                        .HasForeignKey("PromptTemplateId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Dhole.AI.Domain.Profiles.Entities.AiProfileModel", b =>
                {
                    b.HasOne("Dhole.AI.Domain.Models.Entities.AiModel", null)
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dhole.AI.Domain.Profiles.Entities.AiProfile", null)
                        .WithMany("Models")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_ai_profile_models_ai_profiles_ai_profile_id");
                });

            modelBuilder.Entity("Dhole.AI.Domain.Executions.Entities.AiExecution", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("Dhole.AI.Domain.Profiles.Entities.AiProfile", b =>
                {
                    b.Navigation("Models");
                });
#pragma warning restore 612, 618
        }
    }
}
